; Auto-generated. Do not edit!


(cl:in-package hq_robot_task-msg)


;//! \htmlinclude hq_RobotTaskFeedback.msg.html

(cl:defclass <hq_RobotTaskFeedback> (roslisp-msg-protocol:ros-message)
  ((complete
    :reader complete
    :initarg :complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass hq_RobotTaskFeedback (<hq_RobotTaskFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <hq_RobotTaskFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'hq_RobotTaskFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hq_robot_task-msg:<hq_RobotTaskFeedback> is deprecated: use hq_robot_task-msg:hq_RobotTaskFeedback instead.")))

(cl:ensure-generic-function 'complete-val :lambda-list '(m))
(cl:defmethod complete-val ((m <hq_RobotTaskFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hq_robot_task-msg:complete-val is deprecated.  Use hq_robot_task-msg:complete instead.")
  (complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <hq_RobotTaskFeedback>) ostream)
  "Serializes a message object of type '<hq_RobotTaskFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <hq_RobotTaskFeedback>) istream)
  "Deserializes a message object of type '<hq_RobotTaskFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<hq_RobotTaskFeedback>)))
  "Returns string type for a message object of type '<hq_RobotTaskFeedback>"
  "hq_robot_task/hq_RobotTaskFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'hq_RobotTaskFeedback)))
  "Returns string type for a message object of type 'hq_RobotTaskFeedback"
  "hq_robot_task/hq_RobotTaskFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<hq_RobotTaskFeedback>)))
  "Returns md5sum for a message object of type '<hq_RobotTaskFeedback>"
  "400345d77a70d48b24323a6a2a59ab1e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'hq_RobotTaskFeedback)))
  "Returns md5sum for a message object of type 'hq_RobotTaskFeedback"
  "400345d77a70d48b24323a6a2a59ab1e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<hq_RobotTaskFeedback>)))
  "Returns full string definition for message of type '<hq_RobotTaskFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'hq_RobotTaskFeedback)))
  "Returns full string definition for message of type 'hq_RobotTaskFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <hq_RobotTaskFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <hq_RobotTaskFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'hq_RobotTaskFeedback
    (cl:cons ':complete (complete msg))
))
