// Generated by gencpp from file am_driver/CurrentStatus.msg
// DO NOT EDIT!


#ifndef AM_DRIVER_MESSAGE_CURRENTSTATUS_H
#define AM_DRIVER_MESSAGE_CURRENTSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace am_driver
{
template <class ContainerAllocator>
struct CurrentStatus_
{
  typedef CurrentStatus_<ContainerAllocator> Type;

  CurrentStatus_()
    : header()
    , state(0)
    , subState(0)
    , mode(0)  {
    }
  CurrentStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , subState(0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _state_type;
  _state_type state;

   typedef int16_t _subState_type;
  _subState_type subState;

   typedef int16_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::am_driver::CurrentStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_driver::CurrentStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentStatus_

typedef ::am_driver::CurrentStatus_<std::allocator<void> > CurrentStatus;

typedef boost::shared_ptr< ::am_driver::CurrentStatus > CurrentStatusPtr;
typedef boost::shared_ptr< ::am_driver::CurrentStatus const> CurrentStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_driver::CurrentStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_driver::CurrentStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'am_driver': ['/home/alberto/Documents/catkin_ws/src/hrp/am_driver/msg', '/home/alberto/Documents/catkin_ws/src/hrp/am_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::CurrentStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::CurrentStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::CurrentStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::CurrentStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::CurrentStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::CurrentStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_driver::CurrentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c9ffe94e8f0a9d6014780d8cebb049b";
  }

  static const char* value(const ::am_driver::CurrentStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c9ffe94e8f0a9d6ULL;
  static const uint64_t static_value2 = 0x014780d8cebb049bULL;
};

template<class ContainerAllocator>
struct DataType< ::am_driver::CurrentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_driver/CurrentStatus";
  }

  static const char* value(const ::am_driver::CurrentStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_driver::CurrentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Topic that is meant to reflect contents of command family \"CurrentStatus\" with command \"GetStatusKeepAlive\" from Automower TIF\n\
\n\
Header header\n\
\n\
# -1 = undefined\n\
# 0 = Power-up state\n\
# 1 = Waiting state\n\
# 2 = Irregular cutting state\n\
# 3 = Searching CS state\n\
# 4 = Charging state\n\
# 5 = Leaving CS state\n\
# 6 = SW downloading state\n\
# 7 = Fault state. Fatal Error\n\
# 8 = Fault state. Error\n\
int16 state\n\
\n\
# -1 = undefined\n\
# 0 = No sub status\n\
# 1 = Irregular moving\n\
# 2 = Complex outside\n\
# 3 = Complex wheels blocked\n\
# 4 = Complex wheels slipped\n\
# 5 = Complex outside at reverse\n\
# 6 = Complex collision\n\
# 7 = Complex lifted\n\
# 8 = Local intensive cutting\n\
# 9 = Follow guide wire 1 in\n\
# 10 = Follow right boundary wire in\n\
# 11 = Docking\n\
# 12 = Fast charging\n\
# 13 = Top-up charging\n\
# 14 = Charging ready\n\
# 15 = Exit angle\n\
# 16 = Follow guide wire 1 out\n\
# 17 = Follow right boundary wire out\n\
# 18 = Complex No Loop Signal\n\
# 19 = Complex Cutting Means blocked\n\
# 20 = Complex Cutting Means blocked\n\
# 21 = Follow guide wire 2 in\n\
# 22 = Follow guide wire 3 in\n\
# 23 = Follow guide wire 2 out\n\
# 24 = Follow guide wire 3 out\n\
# 25 = Follow left boundary wire in\n\
# 26 = Follow left boundary wire out\n\
# 27 = Complex too steep slope\n\
int16 subState\n\
\n\
# -1 = undefined\n\
# 0 = Power-down mode\n\
# 1 = Standby mode\n\
# 2 = Sleep mode\n\
# 3 = Sub -active mode\n\
# 4 = Boot mode\n\
# 5 = Idle mode\n\
# 6 = Auto mode\n\
# 7 = Manual mode\n\
# 8 = Home mode\n\
int16 mode\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::am_driver::CurrentStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_driver::CurrentStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.subState);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_driver::CurrentStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_driver::CurrentStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int16_t>::stream(s, indent + "  ", v.state);
    s << indent << "subState: ";
    Printer<int16_t>::stream(s, indent + "  ", v.subState);
    s << indent << "mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_DRIVER_MESSAGE_CURRENTSTATUS_H
