// Generated by gencpp from file am_driver/MotorFeedbackDiffDrive.msg
// DO NOT EDIT!


#ifndef AM_DRIVER_MESSAGE_MOTORFEEDBACKDIFFDRIVE_H
#define AM_DRIVER_MESSAGE_MOTORFEEDBACKDIFFDRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <am_driver/MotorFeedback.h>
#include <am_driver/MotorFeedback.h>

namespace am_driver
{
template <class ContainerAllocator>
struct MotorFeedbackDiffDrive_
{
  typedef MotorFeedbackDiffDrive_<ContainerAllocator> Type;

  MotorFeedbackDiffDrive_()
    : header()
    , left()
    , right()  {
    }
  MotorFeedbackDiffDrive_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::am_driver::MotorFeedback_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::am_driver::MotorFeedback_<ContainerAllocator>  _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> const> ConstPtr;

}; // struct MotorFeedbackDiffDrive_

typedef ::am_driver::MotorFeedbackDiffDrive_<std::allocator<void> > MotorFeedbackDiffDrive;

typedef boost::shared_ptr< ::am_driver::MotorFeedbackDiffDrive > MotorFeedbackDiffDrivePtr;
typedef boost::shared_ptr< ::am_driver::MotorFeedbackDiffDrive const> MotorFeedbackDiffDriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'am_driver': ['/home/alberto/Documents/catkin_ws/src/hrp/am_driver/msg', '/home/alberto/Documents/catkin_ws/src/hrp/am_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17ed5e1da280dd97ff21ded1ea2d0771";
  }

  static const char* value(const ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17ed5e1da280dd97ULL;
  static const uint64_t static_value2 = 0xff21ded1ea2d0771ULL;
};

template<class ContainerAllocator>
struct DataType< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_driver/MotorFeedbackDiffDrive";
  }

  static const char* value(const ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
MotorFeedback left\n\
MotorFeedback right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: am_driver/MotorFeedback\n\
Header header\n\
float32 omega\n\
float32 current\n\
int32 ticks\n\
float32 controlOmega\n\
float32 controlPower\n\
bool hold_position\n\
";
  }

  static const char* value(const ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorFeedbackDiffDrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_driver::MotorFeedbackDiffDrive_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::am_driver::MotorFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::am_driver::MotorFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_DRIVER_MESSAGE_MOTORFEEDBACKDIFFDRIVE_H
