(cl:defpackage hq_robot_task-msg
  (:use )
  (:export
   "<HQ_ROBOTTASKACTION>"
   "HQ_ROBOTTASKACTION"
   "<HQ_ROBOTTASKACTIONFEEDBACK>"
   "HQ_ROBOTTASKACTIONFEEDBACK"
   "<HQ_ROBOTTASKACTIONGOAL>"
   "HQ_ROBOTTASKACTIONGOAL"
   "<HQ_ROBOTTASKACTIONRESULT>"
   "HQ_ROBOTTASKACTIONRESULT"
   "<HQ_ROBOTTASKFEEDBACK>"
   "HQ_ROBOTTASKFEEDBACK"
   "<HQ_ROBOTTASKGOAL>"
   "HQ_ROBOTTASKGOAL"
   "<HQ_ROBOTTASKRESULT>"
   "HQ_ROBOTTASKRESULT"
  ))

