// Generated by gencpp from file am_driver_safe/TifCmdResponse.msg
// DO NOT EDIT!


#ifndef AM_DRIVER_SAFE_MESSAGE_TIFCMDRESPONSE_H
#define AM_DRIVER_SAFE_MESSAGE_TIFCMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace am_driver_safe
{
template <class ContainerAllocator>
struct TifCmdResponse_
{
  typedef TifCmdResponse_<ContainerAllocator> Type;

  TifCmdResponse_()
    : str()  {
    }
  TifCmdResponse_(const ContainerAllocator& _alloc)
    : str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TifCmdResponse_

typedef ::am_driver_safe::TifCmdResponse_<std::allocator<void> > TifCmdResponse;

typedef boost::shared_ptr< ::am_driver_safe::TifCmdResponse > TifCmdResponsePtr;
typedef boost::shared_ptr< ::am_driver_safe::TifCmdResponse const> TifCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_driver_safe::TifCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_driver_safe

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const ::am_driver_safe::TifCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x994972b6e03928b2ULL;
  static const uint64_t static_value2 = 0x476860ce6c4c8e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_driver_safe/TifCmdResponse";
  }

  static const char* value(const ::am_driver_safe::TifCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str\n\
";
  }

  static const char* value(const ::am_driver_safe::TifCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TifCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_driver_safe::TifCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_driver_safe::TifCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_DRIVER_SAFE_MESSAGE_TIFCMDRESPONSE_H
