// Generated by gencpp from file am_driver_safe/turnOfLoopCmdRequest.msg
// DO NOT EDIT!


#ifndef AM_DRIVER_SAFE_MESSAGE_TURNOFLOOPCMDREQUEST_H
#define AM_DRIVER_SAFE_MESSAGE_TURNOFLOOPCMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace am_driver_safe
{
template <class ContainerAllocator>
struct turnOfLoopCmdRequest_
{
  typedef turnOfLoopCmdRequest_<ContainerAllocator> Type;

  turnOfLoopCmdRequest_()
    {
    }
  turnOfLoopCmdRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct turnOfLoopCmdRequest_

typedef ::am_driver_safe::turnOfLoopCmdRequest_<std::allocator<void> > turnOfLoopCmdRequest;

typedef boost::shared_ptr< ::am_driver_safe::turnOfLoopCmdRequest > turnOfLoopCmdRequestPtr;
typedef boost::shared_ptr< ::am_driver_safe::turnOfLoopCmdRequest const> turnOfLoopCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_driver_safe

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_driver_safe/turnOfLoopCmdRequest";
  }

  static const char* value(const ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turnOfLoopCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::am_driver_safe::turnOfLoopCmdRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AM_DRIVER_SAFE_MESSAGE_TURNOFLOOPCMDREQUEST_H
