// Generated by gencpp from file hq_robot_task/hq_RobotTaskResult.msg
// DO NOT EDIT!


#ifndef HQ_ROBOT_TASK_MESSAGE_HQ_ROBOTTASKRESULT_H
#define HQ_ROBOT_TASK_MESSAGE_HQ_ROBOTTASKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hq_robot_task
{
template <class ContainerAllocator>
struct hq_RobotTaskResult_
{
  typedef hq_RobotTaskResult_<ContainerAllocator> Type;

  hq_RobotTaskResult_()
    : success(0)
    , description()
    , plan()  {
    }
  hq_RobotTaskResult_(const ContainerAllocator& _alloc)
    : success(0)
    , description(_alloc)
    , plan(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _plan_type;
  _plan_type plan;





  typedef boost::shared_ptr< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> const> ConstPtr;

}; // struct hq_RobotTaskResult_

typedef ::hq_robot_task::hq_RobotTaskResult_<std::allocator<void> > hq_RobotTaskResult;

typedef boost::shared_ptr< ::hq_robot_task::hq_RobotTaskResult > hq_RobotTaskResultPtr;
typedef boost::shared_ptr< ::hq_robot_task::hq_RobotTaskResult const> hq_RobotTaskResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hq_robot_task

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hq_robot_task': ['/home/alberto/Documents/catkin_ws/devel/share/hq_robot_task/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a3ce67db61409507027bbc08434f3e8";
  }

  static const char* value(const ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a3ce67db6140950ULL;
  static const uint64_t static_value2 = 0x7027bbc08434f3e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hq_robot_task/hq_RobotTaskResult";
  }

  static const char* value(const ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
int32 success\n\
string description\n\
string plan\n\
";
  }

  static const char* value(const ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.description);
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hq_RobotTaskResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hq_robot_task::hq_RobotTaskResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int32_t>::stream(s, indent + "  ", v.success);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "plan: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HQ_ROBOT_TASK_MESSAGE_HQ_ROBOTTASKRESULT_H
