// Generated by gencpp from file am_driver/MotorFeedback.msg
// DO NOT EDIT!


#ifndef AM_DRIVER_MESSAGE_MOTORFEEDBACK_H
#define AM_DRIVER_MESSAGE_MOTORFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace am_driver
{
template <class ContainerAllocator>
struct MotorFeedback_
{
  typedef MotorFeedback_<ContainerAllocator> Type;

  MotorFeedback_()
    : header()
    , omega(0.0)
    , current(0.0)
    , ticks(0)
    , controlOmega(0.0)
    , controlPower(0.0)
    , hold_position(false)  {
    }
  MotorFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , omega(0.0)
    , current(0.0)
    , ticks(0)
    , controlOmega(0.0)
    , controlPower(0.0)
    , hold_position(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _omega_type;
  _omega_type omega;

   typedef float _current_type;
  _current_type current;

   typedef int32_t _ticks_type;
  _ticks_type ticks;

   typedef float _controlOmega_type;
  _controlOmega_type controlOmega;

   typedef float _controlPower_type;
  _controlPower_type controlPower;

   typedef uint8_t _hold_position_type;
  _hold_position_type hold_position;





  typedef boost::shared_ptr< ::am_driver::MotorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_driver::MotorFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MotorFeedback_

typedef ::am_driver::MotorFeedback_<std::allocator<void> > MotorFeedback;

typedef boost::shared_ptr< ::am_driver::MotorFeedback > MotorFeedbackPtr;
typedef boost::shared_ptr< ::am_driver::MotorFeedback const> MotorFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_driver::MotorFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_driver::MotorFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'am_driver': ['/home/alberto/Documents/catkin_ws/src/hrp/am_driver/msg', '/home/alberto/Documents/catkin_ws/src/hrp/am_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::MotorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::MotorFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::MotorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::MotorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::MotorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::MotorFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_driver::MotorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a82b11e9d653840123adaac181515b35";
  }

  static const char* value(const ::am_driver::MotorFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa82b11e9d6538401ULL;
  static const uint64_t static_value2 = 0x23adaac181515b35ULL;
};

template<class ContainerAllocator>
struct DataType< ::am_driver::MotorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_driver/MotorFeedback";
  }

  static const char* value(const ::am_driver::MotorFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_driver::MotorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 omega\n\
float32 current\n\
int32 ticks\n\
float32 controlOmega\n\
float32 controlPower\n\
bool hold_position\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::am_driver::MotorFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_driver::MotorFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.omega);
      stream.next(m.current);
      stream.next(m.ticks);
      stream.next(m.controlOmega);
      stream.next(m.controlPower);
      stream.next(m.hold_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_driver::MotorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_driver::MotorFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "omega: ";
    Printer<float>::stream(s, indent + "  ", v.omega);
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
    s << indent << "ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ticks);
    s << indent << "controlOmega: ";
    Printer<float>::stream(s, indent + "  ", v.controlOmega);
    s << indent << "controlPower: ";
    Printer<float>::stream(s, indent + "  ", v.controlPower);
    s << indent << "hold_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hold_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_DRIVER_MESSAGE_MOTORFEEDBACK_H
